version: '3'

services:
  backend1:
    build:
      context: .
      dockerfile: Dockerfile.backend1
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - my-network


networks:
  my-network:
    driver: bridge

